on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 4 * * 0' # every monday morning
  workflow_dispatch:
name: Weekly Dependency Update

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: |
          go version
          make dev-upgrade
      - uses: ./.github/workflows/automatic-tests.yaml

  # todo if passes => crete PR