on:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron:  '0 4 * * 0' # every monday morning
  workflow_dispatch:
name: Weekly Dependency Update

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Update All Dependencies
        run: |
          go version
          make dev-upgrade

      # Enable permissions in GitHub repository or organisation settings: Actions > General > Workflow permissions.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Weekly Dependency Update
          body: Automated upgrade of all dependencies via `make dev-upgrade`
          commit-message: 'chore: automated update'
          token: ${{ secrets.PAT }} # trigger automated-tests workflow, see: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
